In [1]:
import numpy as np 
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies_data = pd.read_excel('finals.xlsx')

In [3]:
movies_data

Name_of_movie  \
0                           Lưỡi Cưa   
1    Harry Potter và Hòn Đá Phù Thủy   
2              Kẻ Sát Nhân Cuồng Tín   
3                   Ngôi Nhà Toàn Ma   
4     Chuyện Ngày Xưa Ở... Hollywood   
..                               ...   
195                À bout de souffle   
196                        Cape Fear   
197                The Lady Vanishes   
198               La planète sauvage   
199       The Muppet Christmas Carol   

                                           Description            Director  \
0    Two strangers awaken in a room with no recolle...           James Wan   
1    An orphaned boy enrolls in a school of wizardr...      Chris Columbus   
2    A wealthy New York City investment banking exe...         Mary Harron   
3    In 1945, immediately following the end of Seco...  Alejandro Amenábar   
4    A faded television actor and his stunt double ...   Quentin Tarantino   
..                                                 ...                 ...   
195  A small-time thief steals a car and impulsivel...     Jean-Luc Godard   
196  A lawyer's family is stalked by a man he once ...     J. Lee Thompson   
197  While travelling in continental Europe, a rich...    Alfred Hitchcock   
198  On a faraway planet where blue giants rule, op...         René Laloux   
199  The Muppets present their own touching renditi...        Brian Henson   

                                                  Star  Index  
0    Cary Elwes  Leigh Whannell  Danny Glover  Ken ...      0  
1    Daniel Radcliffe  Rupert Grint  Richard Harris...      1  
2    Christian Bale  Justin Theroux  Josh Lucas  Bi...      2  
3    Nicole Kidman  Christopher Eccleston  Fionnula...      3  
4    Leonardo DiCaprio  Brad Pitt  Margot Robbie  E...      4  
..                                                 ...    ...  
195  Jean-Paul Belmondo  Jean Seberg  Van Doude  Je...    195  
196  Gregory Peck  Robert Mitchum  Polly Bergen  Lo...    196  
197  Margaret Lockwood  Michael Redgrave  Paul Luka...    197  
198  Barry Bostwick  Jennifer Drake  Eric Baugin  J...    198  
199  Michael Caine  Dave Goelz  Steve Whitmire  Jer...    199  

[200 rows x 5 columns]

In [4]:
import pandas as pd

# Thêm cột index bằng cách sử dụng hàm reset_index
#movies_data['Index'] = movies_data.reset_index().index

# Lưu lại tệp Excel với cột index mới
#movies_data.to_excel('Finals.xlsx', index=False)

In [5]:
movies_data

Name_of_movie  \
0                           Lưỡi Cưa   
1    Harry Potter và Hòn Đá Phù Thủy   
2              Kẻ Sát Nhân Cuồng Tín   
3                   Ngôi Nhà Toàn Ma   
4     Chuyện Ngày Xưa Ở... Hollywood   
..                               ...   
195                À bout de souffle   
196                        Cape Fear   
197                The Lady Vanishes   
198               La planète sauvage   
199       The Muppet Christmas Carol   

                                           Description            Director  \
0    Two strangers awaken in a room with no recolle...           James Wan   
1    An orphaned boy enrolls in a school of wizardr...      Chris Columbus   
2    A wealthy New York City investment banking exe...         Mary Harron   
3    In 1945, immediately following the end of Seco...  Alejandro Amenábar   
4    A faded television actor and his stunt double ...   Quentin Tarantino   
..                                                 ...                 ...   
195  A small-time thief steals a car and impulsivel...     Jean-Luc Godard   
196  A lawyer's family is stalked by a man he once ...     J. Lee Thompson   
197  While travelling in continental Europe, a rich...    Alfred Hitchcock   
198  On a faraway planet where blue giants rule, op...         René Laloux   
199  The Muppets present their own touching renditi...        Brian Henson   

                                                  Star  Index  
0    Cary Elwes  Leigh Whannell  Danny Glover  Ken ...      0  
1    Daniel Radcliffe  Rupert Grint  Richard Harris...      1  
2    Christian Bale  Justin Theroux  Josh Lucas  Bi...      2  
3    Nicole Kidman  Christopher Eccleston  Fionnula...      3  
4    Leonardo DiCaprio  Brad Pitt  Margot Robbie  E...      4  
..                                                 ...    ...  
195  Jean-Paul Belmondo  Jean Seberg  Van Doude  Je...    195  
196  Gregory Peck  Robert Mitchum  Polly Bergen  Lo...    196  
197  Margaret Lockwood  Michael Redgrave  Paul Luka...    197  
198  Barry Bostwick  Jennifer Drake  Eric Baugin  J...    198  
199  Michael Caine  Dave Goelz  Steve Whitmire  Jer...    199  

[200 rows x 5 columns]

In [6]:
movies_data.shape

(200, 5)

In [7]:
selected_features = ['Name_of_movie','Description','Director','Star']
print(selected_features)

['Name_of_movie', 'Description', 'Director', 'Star']


In [8]:
for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')

In [9]:
combined_features = movies_data['Name_of_movie']+' '+movies_data['Description']+' '+movies_data['Director']+' '+movies_data['Star']+' '

In [10]:
print(combined_features)

0      Lưỡi Cưa Two strangers awaken in a room with n...
1      Harry Potter và Hòn Đá Phù Thủy An orphaned bo...
2      Kẻ Sát Nhân Cuồng Tín A wealthy New York City ...
3      Ngôi Nhà Toàn Ma In 1945, immediately followin...
4      Chuyện Ngày Xưa Ở... Hollywood A faded televis...
                             ...                        
195    À bout de souffle A small-time thief steals a ...
196    Cape Fear A lawyer's family is stalked by a ma...
197    The Lady Vanishes While travelling in continen...
198    La planète sauvage On a faraway planet where b...
199    The Muppet Christmas Carol The Muppets present...
Length: 200, dtype: object


In [11]:
vectorizer = TfidfVectorizer()

In [12]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [13]:
print(feature_vectors)

  (0, 1916)	0.17391439198769212
  (0, 1793)	0.17391439198769212
  (0, 1342)	0.1643015183033159
  (0, 818)	0.14560200103635942
  (0, 3584)	0.18746297648740595
  (0, 1898)	0.1643015183033159
  (0, 1041)	0.18746297648740595
  (0, 544)	0.18746297648740595
  (0, 3543)	0.17391439198769212
  (0, 1694)	0.11404289111979825
  (0, 1811)	0.15684519419529852
  (0, 2929)	0.18746297648740595
  (0, 2361)	0.17391439198769212
  (0, 481)	0.0918227605601619
  (0, 2498)	0.18746297648740595
  (0, 1274)	0.1643015183033159
  (0, 840)	0.18746297648740595
  (0, 2480)	0.17391439198769212
  (0, 2685)	0.18746297648740595
  (0, 927)	0.15684519419529852
  (0, 3037)	0.15684519419529852
  (0, 163)	0.056081334126960466
  (0, 3239)	0.18746297648740595
  (0, 1368)	0.18746297648740595
  (0, 3245)	0.22104455565423678
  :	:
  (199, 3594)	0.22735864632632152
  (199, 1348)	0.22735864632632152
  (199, 3186)	0.22735864632632152
  (199, 912)	0.22735864632632152
  (199, 2743)	0.22735864632632152
  (199, 3319)	0.22735864632632152


In [14]:
similarity = cosine_similarity(feature_vectors)

In [15]:
print(similarity)

[[1.         0.01380236 0.00298497 ... 0.00819357 0.         0.0032163 ]
 [0.01380236 1.         0.02525083 ... 0.03876341 0.01986444 0.01976437]
 [0.00298497 0.02525083 1.         ... 0.00969991 0.         0.        ]
 ...
 [0.00819357 0.03876341 0.00969991 ... 1.         0.         0.02922815]
 [0.         0.01986444 0.         ... 0.         1.         0.01380436]
 [0.0032163  0.01976437 0.         ... 0.02922815 0.01380436 1.        ]]


In [16]:
print(similarity.shape)

(200, 200)


In [20]:
list_of_all_titles = movies_data['Name_of_movie'].tolist()
print(list_of_all_titles)     

['Lưỡi Cưa', 'Harry Potter và Hòn Đá Phù Thủy', 'Kẻ Sát Nhân Cuồng Tín', 'Ngôi Nhà Toàn Ma', 'Chuyện Ngày Xưa Ở... Hollywood', 'Nhân Tố Thứ 5', 'RoboCop', 'Người Hùng Báo Thù', 'Chúng Ta Làm Gì Trong Bóng Tối', 'The Birds', '300 Chiến Binh', 'Siêu Tệ Hại', 'Deadpool 2', 'The Fly', 'Cách Mạng Công Sở', 'Ánh Sao Ma Thuật', 'My Cousin Vinny', 'Chiến Tranh Giữa Các Vì Sao 3: Người Sith Báo Thù', 'Không Lùi Bước', 'Kung Fu Panda', 'Kẻ Trộm Mặt Trăng', 'Tiền Bi', 'Vệ Binh Dải Ngân Hà 2', 'Vì Sao Vụt Sáng', 'Lằn Ranh Đỏ Mỏng Manh', 'Hiệu Ứng Cánh Bướm', 'Nửa Đêm Ở Paris', 'Bản Báo Cáo Thiểu Số', 'Người Hùng Củ Chuối', 'After Hours', 'Gia Đình Thiên Tài', 'The Invisible Man', 'Gã Thợ Máy', 'Đứa Bé Mất Tích', 'Match Point', 'True Grit: Báo Thù', 'Hang Quỷ Đông Âu', 'Góc Khuất', 'End of Watch', 'Vũ Khí Tối Thượng', 'Cậu Bé Rừng Xanh', 'Max Điên 2: Hung Thần Xa Lộ', 'Đương Đầu Với Thử Thách 3', 'Nhà Mitchell Đối Đầu Với Máy Móc', 'Cô Bé Người Cá Ponyo', 'Truy Tìm Tung Tích Ảo', 'Cái Giá Của Sự Th

In [ ]:
movie_name = input(' Enter your favourite movie name : ')

In [ ]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

In [ ]:
close_match = find_close_match[0]
print(close_match)

In [24]:
index_of_the_movie = movies_data[movies_data.Name_of_movie == close_match]['Index'].values[0]
print(index_of_the_movie)

93


In [25]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.020997037057070612), (1, 0.09052118929554148), (2, 0.007446587101254331), (3, 0.01626962030972389), (4, 0.005772125870352039), (5, 0.013689911866862641), (6, 0.015836361513339673), (7, 0.01364567919137992), (8, 0.007218530919404686), (9, 0.059870624598807376), (10, 0.004108317518918487), (11, 0.004478764173957589), (12, 0.005582675150209168), (13, 0.017874789741034562), (14, 0.0025320736830660925), (15, 0.016241005547103077), (16, 0.005813973329843989), (17, 0.014457826147230849), (18, 0.018784822506865237), (19, 0.03197374788637842), (20, 0.028585242246187144), (21, 0.004311228687515521), (22, 0.017158292647350616), (23, 0.008363857142558351), (24, 0.008135383130534636), (25, 0.010729663833642055), (26, 0.026690051826445595), (27, 0.049725608495249846), (28, 0.009427045960616956), (29, 0.006142083192084402), (30, 0.008400610256195241), (31, 0.01643283792239355), (32, 0.002615896886157031), (33, 0.0), (34, 0.004352965388386423), (35, 0.08623874992504521), (36, 0.0021960241541238

In [26]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(93, 1.0), (55, 0.2307377914964521), (72, 0.1402502368327828), (83, 0.135552677250216), (92, 0.133032193283054), (1, 0.09052118929554148), (35, 0.08623874992504521), (76, 0.0802689621223857), (91, 0.07974340842322958), (162, 0.0697649715566501), (9, 0.059870624598807376), (27, 0.049725608495249846), (123, 0.04164474842699698), (136, 0.04025688908537669), (129, 0.03765967800625264), (176, 0.035032094097393815), (153, 0.034725642940816946), (38, 0.03433939024100407), (180, 0.03262398735660006), (86, 0.032546896026858), (19, 0.03197374788637842), (112, 0.03168214833878279), (64, 0.030181117895092893), (49, 0.029631630877833975), (143, 0.028673967009302446), (20, 0.028585242246187144), (80, 0.028509469158379173), (181, 0.02784032942060849), (188, 0.02777865120917842), (164, 0.027451932294591187), (139, 0.027119776974761645), (104, 0.027065605319676535), (26, 0.026690051826445595), (120, 0.026671637436496233), (169, 0.02409810516205077), (84, 0.023906934136901342), (130, 0.0238771945128237

In [27]:
print('Gợi ý phim : \n')

i = 1

for movie in sorted_similar_movies:
    index = movie[0]
    Name_of_movie_from_index = movies_data[movies_data.index==index]['Name_of_movie'].values[0]
    if (i<30):
        print(i, '.',Name_of_movie_from_index)
        i+=1

Gợi ý phim : 

1 . Dirty Harry
2 . The Bridges of Madison County
3 . Harry Potter và Chiếc Cốc Lửa
4 . Harry Potter và Bảo Bối Tử Thần: Phần 1
5 . When Harry Met Sally...
6 . Harry Potter và Hòn Đá Phù Thủy
7 . True Grit: Báo Thù
8 . Sát Nhân Huyền Thoại
9 . Trò Chơi Ma Quỷ
10 . Invasion of the Body Snatchers
11 . The Birds
12 . Bản Báo Cáo Thiểu Số
13 . Công Nghệ Gen
14 . Philadelphia
15 . Sound of Metal
16 . Tiểu Đội Trừng Giới
17 . Siêu Điệp Viên 2: Quyền Lực Của Bourne
18 . End of Watch
19 . The Longest Day
20 . Mr. Nobody
21 . Kung Fu Panda
22 . Donnie Brasco: Kẻ Nằm Vùng
23 . Phòng Giam 211
24 . The Taking of Pelham One Two Three
25 . Đây Là Nước Anh
26 . Kẻ Trộm Mặt Trăng
27 . Aftersun
28 . Người Mẹ
29 . The Quiet Man


In [28]:
import pickle

In [29]:
pickle.dump(movies_data,open('movie_list.pkl','wb'))


In [30]:
pickle.dump(similarity,open('similarity.pkl','wb'))
